-- Mirrors the live `pre_approved_token_registry` schema documented in
-- docs/Supabase_Info.md. Table currently lives outside this repo's prior
-- migration history (likely created directly / via the forge repo); this
-- file just captures its current shape for reference.
do $$ begin
  create type network_type as enum ('devnet', 'mainnet');
exception
  when duplicate_object then null;
end $$;

create table if not exists pre_approved_token_registry (
  id bigint generated by default as identity primary key,
  network network_type not null,
  asset_id bigint not null,
  mint text not null,
  pool_address text not null,
  pyth_feed_id text not null,
  decimals smallint not null,
  route text not null,
  price_source_tag smallint not null,
  price_dex_kind smallint not null,
  price_pool_address text not null,
  twap jsonb,
  swap_kind text not null,
  token_program_tag smallint not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
