-- Preset reference tables (Pools.md / Vault.md / constant.js / vaultPresets.js).
-- Not on-chain state — templates for Admin → Create asset and Vault Ops → Create ETF.
-- Idempotent: safe to re-run in the Supabase SQL editor.

create table if not exists asset_presets (
  preset_key text primary key,
  asset_name text not null,
  mint text not null,
  pool_address text not null,
  pyth_feed_id text not null,
  decimals smallint not null,
  route text not null check (route in ('ViaSol', 'DirectUsdc')),
  price_source_tag smallint not null,
  price_dex_kind smallint not null,
  swap_kind text not null check (swap_kind in ('Whirlpool', 'DammV2')),
  token_program_tag smallint not null,
  aliases jsonb not null default '[]'::jsonb
);

create table if not exists vault_presets (
  vault_num integer primary key,
  name text not null,
  symbol text not null,
  theme text not null,
  fund_type text not null default 'dynamic' check (fund_type in ('dynamic', 'fixed')),
  deposit_fee_bps integer not null default 0,
  redeem_fee_bps integer not null default 100,
  assets jsonb not null
);

alter table asset_presets enable row level security;
alter table vault_presets enable row level security;

grant select, insert, update on table asset_presets to anon;
grant select, insert, update on table vault_presets to anon;

drop policy if exists "anon read asset_presets" on asset_presets;
drop policy if exists "anon insert asset_presets" on asset_presets;
drop policy if exists "anon update asset_presets" on asset_presets;
drop policy if exists "anon read vault_presets" on vault_presets;
drop policy if exists "anon insert vault_presets" on vault_presets;
drop policy if exists "anon update vault_presets" on vault_presets;

create policy "anon read asset_presets"
  on asset_presets for select to anon using (true);

create policy "anon insert asset_presets"
  on asset_presets for insert to anon with check (true);

create policy "anon update asset_presets"
  on asset_presets for update to anon using (true) with check (true);

create policy "anon read vault_presets"
  on vault_presets for select to anon using (true);

create policy "anon insert vault_presets"
  on vault_presets for insert to anon with check (true);

create policy "anon update vault_presets"
  on vault_presets for update to anon using (true) with check (true);

-- ── asset_presets seed (8 rows from constant.js ASSET_PRESETS) ───────────────

insert into asset_presets (preset_key, asset_name, mint, pool_address, pyth_feed_id, decimals, route, price_source_tag, price_dex_kind, swap_kind, token_program_tag, aliases) values ('wsol', 'SOL', 'So11111111111111111111111111111111111111112', 'Czfq3xZZDmsdGdUyrNLtRhGc47cXcZtLG4crryfu44zE', 'ef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d', 9, 'DirectUsdc', 0, 0, 'Whirlpool', 0, '["sol","wsol","wrapped sol"]') on conflict (preset_key) do update set asset_name = excluded.asset_name, mint = excluded.mint, pool_address = excluded.pool_address, pyth_feed_id = excluded.pyth_feed_id, decimals = excluded.decimals, route = excluded.route, price_source_tag = excluded.price_source_tag, price_dex_kind = excluded.price_dex_kind, swap_kind = excluded.swap_kind, token_program_tag = excluded.token_program_tag, aliases = excluded.aliases;
insert into asset_presets (preset_key, asset_name, mint, pool_address, pyth_feed_id, decimals, route, price_source_tag, price_dex_kind, swap_kind, token_program_tag, aliases) values ('wbtc', 'BTC', '3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh', 'B5EwJVDuAauzUEEdwvbuXzbFFgEYnUqqS37TUM1c4PQA', 'e62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43', 8, 'ViaSol', 0, 0, 'Whirlpool', 0, '["btc","wbtc","bitcoin","wrapped bitcoin"]') on conflict (preset_key) do update set asset_name = excluded.asset_name, mint = excluded.mint, pool_address = excluded.pool_address, pyth_feed_id = excluded.pyth_feed_id, decimals = excluded.decimals, route = excluded.route, price_source_tag = excluded.price_source_tag, price_dex_kind = excluded.price_dex_kind, swap_kind = excluded.swap_kind, token_program_tag = excluded.token_program_tag, aliases = excluded.aliases;
insert into asset_presets (preset_key, asset_name, mint, pool_address, pyth_feed_id, decimals, route, price_source_tag, price_dex_kind, swap_kind, token_program_tag, aliases) values ('weth', 'ETH', '7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs', 'HktfL7iwGKT5QHjywQkcDnZXScoh811k7akrMZJkCcEF', 'ff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace', 8, 'ViaSol', 0, 0, 'Whirlpool', 0, '["eth","weth","ethereum","wrapped ethereum"]') on conflict (preset_key) do update set asset_name = excluded.asset_name, mint = excluded.mint, pool_address = excluded.pool_address, pyth_feed_id = excluded.pyth_feed_id, decimals = excluded.decimals, route = excluded.route, price_source_tag = excluded.price_source_tag, price_dex_kind = excluded.price_dex_kind, swap_kind = excluded.swap_kind, token_program_tag = excluded.token_program_tag, aliases = excluded.aliases;
insert into asset_presets (preset_key, asset_name, mint, pool_address, pyth_feed_id, decimals, route, price_source_tag, price_dex_kind, swap_kind, token_program_tag, aliases) values ('w26', 'W26', 'AYYfBtUEwQp5ynUD4AUd8azoyxgtp7oH7QsSBvCmmoon', '3AK56LD4ih9uKGuAUwJ7MuhABAcibiwj3g5hE9ky5d9w', '0000000000000000000000000000000000000000000000000000000000000000', 6, 'DirectUsdc', 1, 1, 'DammV2', 0, '["w26","w26-usdc","w26usdc","w26 usdc"]') on conflict (preset_key) do update set asset_name = excluded.asset_name, mint = excluded.mint, pool_address = excluded.pool_address, pyth_feed_id = excluded.pyth_feed_id, decimals = excluded.decimals, route = excluded.route, price_source_tag = excluded.price_source_tag, price_dex_kind = excluded.price_dex_kind, swap_kind = excluded.swap_kind, token_program_tag = excluded.token_program_tag, aliases = excluded.aliases;
insert into asset_presets (preset_key, asset_name, mint, pool_address, pyth_feed_id, decimals, route, price_source_tag, price_dex_kind, swap_kind, token_program_tag, aliases) values ('nest', 'NEST', '68Nq68CrtLVpyvK5Un7UADiNczaGf39hBbj3diRsYj6D', 'FpqhEG281t5Bi6yT782ieQkpzmPMRyBY5oirK1rcwCH1', 'ef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d', 9, 'ViaSol', 1, 1, 'DammV2', 0, '["nest","nest-sol","nestsol","nest sol"]') on conflict (preset_key) do update set asset_name = excluded.asset_name, mint = excluded.mint, pool_address = excluded.pool_address, pyth_feed_id = excluded.pyth_feed_id, decimals = excluded.decimals, route = excluded.route, price_source_tag = excluded.price_source_tag, price_dex_kind = excluded.price_dex_kind, swap_kind = excluded.swap_kind, token_program_tag = excluded.token_program_tag, aliases = excluded.aliases;
insert into asset_presets (preset_key, asset_name, mint, pool_address, pyth_feed_id, decimals, route, price_source_tag, price_dex_kind, swap_kind, token_program_tag, aliases) values ('spcx', 'SPCX', 'SPCXxcqXj6e5dJDVNovHN8744zkbhM2bYudU45BimGb', 'FgjxPHeYsq1axH29fnGKZi6UyRWi4tMPHgu1gc3ezA9U', '0000000000000000000000000000000000000000000000000000000000000000', 6, 'DirectUsdc', 1, 0, 'Whirlpool', 1, '["spcx","spcx-usdc","spcxusdc","spcx / usdc","spcx/usdc"]') on conflict (preset_key) do update set asset_name = excluded.asset_name, mint = excluded.mint, pool_address = excluded.pool_address, pyth_feed_id = excluded.pyth_feed_id, decimals = excluded.decimals, route = excluded.route, price_source_tag = excluded.price_source_tag, price_dex_kind = excluded.price_dex_kind, swap_kind = excluded.swap_kind, token_program_tag = excluded.token_program_tag, aliases = excluded.aliases;
insert into asset_presets (preset_key, asset_name, mint, pool_address, pyth_feed_id, decimals, route, price_source_tag, price_dex_kind, swap_kind, token_program_tag, aliases) values ('jup', 'JUP', 'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN', 'C1MgLojNLWBKADvu9BHdtgzz1oZX4dZ5zGdGcgvvW8Wz', 'ef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d', 6, 'ViaSol', 1, 0, 'Whirlpool', 0, '["jup","jup-sol","jupsol","jup / sol","jup/sol","jupiter"]') on conflict (preset_key) do update set asset_name = excluded.asset_name, mint = excluded.mint, pool_address = excluded.pool_address, pyth_feed_id = excluded.pyth_feed_id, decimals = excluded.decimals, route = excluded.route, price_source_tag = excluded.price_source_tag, price_dex_kind = excluded.price_dex_kind, swap_kind = excluded.swap_kind, token_program_tag = excluded.token_program_tag, aliases = excluded.aliases;
insert into asset_presets (preset_key, asset_name, mint, pool_address, pyth_feed_id, decimals, route, price_source_tag, price_dex_kind, swap_kind, token_program_tag, aliases) values ('nvda', 'NVDAx', 'Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh', '6R4r93V5fcMzc13CL2enEepDSYcr4Qx3ptZBDwudTXCo', '0000000000000000000000000000000000000000000000000000000000000000', 8, 'DirectUsdc', 1, 0, 'Whirlpool', 1, '["nvda","nvdax","nvda-usdc","nvda / usdc","nvda/usdc","nvidia"]') on conflict (preset_key) do update set asset_name = excluded.asset_name, mint = excluded.mint, pool_address = excluded.pool_address, pyth_feed_id = excluded.pyth_feed_id, decimals = excluded.decimals, route = excluded.route, price_source_tag = excluded.price_source_tag, price_dex_kind = excluded.price_dex_kind, swap_kind = excluded.swap_kind, token_program_tag = excluded.token_program_tag, aliases = excluded.aliases;

-- ── vault_presets seed (10 rows from lib/vaultPresets.js) ───────────────────

insert into vault_presets (vault_num, name, symbol, theme, fund_type, deposit_fee_bps, redeem_fee_bps, assets) values (1, 'Blue Chip Trio', 'BCT3', 'Pyth majors only — smoke test after genesis + two create_asset calls', 'dynamic', 0, 100, '[{"assetId":0,"allocationBps":4000,"role":"L1 anchor (Pyth)"},{"assetId":1,"allocationBps":3500,"role":"BTC store-of-value (Pyth)"},{"assetId":2,"allocationBps":2500,"role":"ETH beta (Pyth)"}]'::jsonb) on conflict (vault_num) do update set name = excluded.name, symbol = excluded.symbol, theme = excluded.theme, fund_type = excluded.fund_type, deposit_fee_bps = excluded.deposit_fee_bps, redeem_fee_bps = excluded.redeem_fee_bps, assets = excluded.assets;
insert into vault_presets (vault_num, name, symbol, theme, fund_type, deposit_fee_bps, redeem_fee_bps, assets) values (2, 'Core Four', 'CORE4', 'Large caps + JUP — majors with one Solana DeFi leg', 'dynamic', 0, 100, '[{"assetId":0,"allocationBps":3000,"role":"Core SOL"},{"assetId":1,"allocationBps":2500,"role":"BTC leg"},{"assetId":2,"allocationBps":2500,"role":"ETH leg"},{"assetId":6,"allocationBps":2000,"role":"JUP / Solana DeFi (DEX TWAP)"}]'::jsonb) on conflict (vault_num) do update set name = excluded.name, symbol = excluded.symbol, theme = excluded.theme, fund_type = excluded.fund_type, deposit_fee_bps = excluded.deposit_fee_bps, redeem_fee_bps = excluded.redeem_fee_bps, assets = excluded.assets;
insert into vault_presets (vault_num, name, symbol, theme, fund_type, deposit_fee_bps, redeem_fee_bps, assets) values (3, 'DEX Quad', 'DEX4', 'Pools.md DEX tokens only — no WBTC/WETH', 'dynamic', 0, 100, '[{"assetId":0,"allocationBps":2500,"role":"wSOL anchor"},{"assetId":3,"allocationBps":2500,"role":"W26-USDC (DAMM v2)"},{"assetId":4,"allocationBps":2500,"role":"NEST-SOL (DAMM v2)"},{"assetId":6,"allocationBps":2500,"role":"JUP-SOL (Whirlpool)"}]'::jsonb) on conflict (vault_num) do update set name = excluded.name, symbol = excluded.symbol, theme = excluded.theme, fund_type = excluded.fund_type, deposit_fee_bps = excluded.deposit_fee_bps, redeem_fee_bps = excluded.redeem_fee_bps, assets = excluded.assets;
insert into vault_presets (vault_num, name, symbol, theme, fund_type, deposit_fee_bps, redeem_fee_bps, assets) values (4, 'Balanced Five', 'BAL5', 'Majors + meme/alt DEX legs — balanced risk', 'dynamic', 0, 100, '[{"assetId":0,"allocationBps":2500,"role":"SOL core"},{"assetId":1,"allocationBps":2000,"role":"BTC"},{"assetId":2,"allocationBps":2000,"role":"ETH"},{"assetId":5,"allocationBps":2000,"role":"SPCX-USDC (Whirlpool, Token-2022)"},{"assetId":6,"allocationBps":1500,"role":"JUP-SOL"}]'::jsonb) on conflict (vault_num) do update set name = excluded.name, symbol = excluded.symbol, theme = excluded.theme, fund_type = excluded.fund_type, deposit_fee_bps = excluded.deposit_fee_bps, redeem_fee_bps = excluded.redeem_fee_bps, assets = excluded.assets;
insert into vault_presets (vault_num, name, symbol, theme, fund_type, deposit_fee_bps, redeem_fee_bps, assets) values (5, 'TWAP Penta', 'TWP5', 'Full TWAP coverage — every DEX-priced preset from Pools.md', 'dynamic', 0, 100, '[{"assetId":0,"allocationBps":2000,"role":"Pyth anchor"},{"assetId":3,"allocationBps":2000,"role":"W26 DirectUsdc TWAP"},{"assetId":4,"allocationBps":2000,"role":"NEST ViaSol TWAP"},{"assetId":5,"allocationBps":2000,"role":"SPCX DirectUsdc TWAP"},{"assetId":6,"allocationBps":2000,"role":"JUP ViaSol TWAP"}]'::jsonb) on conflict (vault_num) do update set name = excluded.name, symbol = excluded.symbol, theme = excluded.theme, fund_type = excluded.fund_type, deposit_fee_bps = excluded.deposit_fee_bps, redeem_fee_bps = excluded.redeem_fee_bps, assets = excluded.assets;
insert into vault_presets (vault_num, name, symbol, theme, fund_type, deposit_fee_bps, redeem_fee_bps, assets) values (6, 'Six Mix', 'MIX6', 'Even-ish blend — majors tilt + DAMM alts', 'dynamic', 0, 100, '[{"assetId":0,"allocationBps":2200,"role":"SOL overweight"},{"assetId":1,"allocationBps":1800,"role":"BTC"},{"assetId":2,"allocationBps":1800,"role":"ETH"},{"assetId":3,"allocationBps":1500,"role":"W26"},{"assetId":4,"allocationBps":1400,"role":"NEST"},{"assetId":6,"allocationBps":1300,"role":"JUP"}]'::jsonb) on conflict (vault_num) do update set name = excluded.name, symbol = excluded.symbol, theme = excluded.theme, fund_type = excluded.fund_type, deposit_fee_bps = excluded.deposit_fee_bps, redeem_fee_bps = excluded.redeem_fee_bps, assets = excluded.assets;
insert into vault_presets (vault_num, name, symbol, theme, fund_type, deposit_fee_bps, redeem_fee_bps, assets) values (7, 'Seven Star', 'S7', 'Full registry — all seven listed assets, equal-ish weights', 'dynamic', 0, 100, '[{"assetId":0,"allocationBps":1800,"role":"wSOL"},{"assetId":1,"allocationBps":1400,"role":"wBTC"},{"assetId":2,"allocationBps":1400,"role":"wETH"},{"assetId":3,"allocationBps":1400,"role":"W26"},{"assetId":4,"allocationBps":1400,"role":"NEST"},{"assetId":5,"allocationBps":1300,"role":"SPCX"},{"assetId":6,"allocationBps":1300,"role":"JUP"}]'::jsonb) on conflict (vault_num) do update set name = excluded.name, symbol = excluded.symbol, theme = excluded.theme, fund_type = excluded.fund_type, deposit_fee_bps = excluded.deposit_fee_bps, redeem_fee_bps = excluded.redeem_fee_bps, assets = excluded.assets;
insert into vault_presets (vault_num, name, symbol, theme, fund_type, deposit_fee_bps, redeem_fee_bps, assets) values (8, 'Route Blend', 'RBL7', 'Swap-route stress — ViaSol vs DirectUsdc mix', 'dynamic', 0, 100, '[{"assetId":0,"allocationBps":1500,"role":"DirectUsdc (wSOL)"},{"assetId":1,"allocationBps":1600,"role":"ViaSol (wBTC)"},{"assetId":2,"allocationBps":1600,"role":"ViaSol (wETH)"},{"assetId":3,"allocationBps":1400,"role":"DirectUsdc (W26)"},{"assetId":4,"allocationBps":1500,"role":"ViaSol (NEST)"},{"assetId":5,"allocationBps":1200,"role":"DirectUsdc (SPCX)"},{"assetId":6,"allocationBps":1200,"role":"ViaSol (JUP)"}]'::jsonb) on conflict (vault_num) do update set name = excluded.name, symbol = excluded.symbol, theme = excluded.theme, fund_type = excluded.fund_type, deposit_fee_bps = excluded.deposit_fee_bps, redeem_fee_bps = excluded.redeem_fee_bps, assets = excluded.assets;
insert into vault_presets (vault_num, name, symbol, theme, fund_type, deposit_fee_bps, redeem_fee_bps, assets) values (9, 'RWA Quad', 'RWA4', 'RWA equities — wSOL + wETH anchors, NVDAx + SPCX (Token-2022)', 'dynamic', 0, 100, '[{"assetId":0,"allocationBps":2500,"role":"wSOL anchor (Pyth)"},{"assetId":2,"allocationBps":2500,"role":"wETH (Pyth)"},{"assetId":7,"allocationBps":2500,"role":"NVDAx/USDC (DEX TWAP, Token-2022)"},{"assetId":5,"allocationBps":2500,"role":"SPCX/USDC (DEX TWAP, Token-2022)"}]'::jsonb) on conflict (vault_num) do update set name = excluded.name, symbol = excluded.symbol, theme = excluded.theme, fund_type = excluded.fund_type, deposit_fee_bps = excluded.deposit_fee_bps, redeem_fee_bps = excluded.redeem_fee_bps, assets = excluded.assets;
insert into vault_presets (vault_num, name, symbol, theme, fund_type, deposit_fee_bps, redeem_fee_bps, assets) values (10, 'Wildcard Eight', 'WLD8', 'Random alt mix — all eight listed assets, no single narrative', 'dynamic', 0, 100, '[{"assetId":0,"allocationBps":1250,"role":"wSOL"},{"assetId":1,"allocationBps":1250,"role":"wBTC"},{"assetId":2,"allocationBps":1250,"role":"wETH"},{"assetId":3,"allocationBps":1250,"role":"W26"},{"assetId":4,"allocationBps":1250,"role":"NEST"},{"assetId":5,"allocationBps":1250,"role":"SPCX"},{"assetId":6,"allocationBps":1250,"role":"JUP"},{"assetId":7,"allocationBps":1250,"role":"NVDAx"}]'::jsonb) on conflict (vault_num) do update set name = excluded.name, symbol = excluded.symbol, theme = excluded.theme, fund_type = excluded.fund_type, deposit_fee_bps = excluded.deposit_fee_bps, redeem_fee_bps = excluded.redeem_fee_bps, assets = excluded.assets;